export interface CI {
  THEME_SWITCH: string;
  GET_USER_AUTH: string;
  LOGOUT: string;
  SET_LOADING: string;
  TRUST_DEVICE: string;
  CHECKIN: string;
  GET_TASK: string;
  ADDING_TASK: string;
  UPDATE_TASK: string;
  DELETE_TASK: string;
  CLEAR_COMPLETED: string;
  FILTER_TASKS: string;
  REORDER_TASK: string;
}

const C: CI = {
  THEME_SWITCH: 'THEME_SWITCH',
  GET_USER_AUTH: ' GET_USER_AUTH',
  LOGOUT: 'LOGOUT',
  SET_LOADING: 'LOADING',
  TRUST_DEVICE: 'TRUST_DEVICE',
  CHECKIN: 'CHECKIN',
  GET_TASK: 'GET_TASK',
  ADDING_TASK: 'ADDING_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
  DELETE_TASK: 'DELETE_TASK',
  CLEAR_COMPLETED: 'CLEAR_ COMPLETED',
  FILTER_TASKS: 'FILTER_TASKS',
  REORDER_TASK: 'REORDER_TASK',
};

export default C;
